/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShioriRouteImport } from './routes/shiori'
import { Route as PromptRouteImport } from './routes/prompt'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SKeyRouteImport } from './routes/s/$key'
import { Route as ApiEncryptRouteImport } from './routes/api/encrypt'
import { Route as ApiDecryptRouteImport } from './routes/api/decrypt'

const ShioriRoute = ShioriRouteImport.update({
  id: '/shiori',
  path: '/shiori',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptRoute = PromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SKeyRoute = SKeyRouteImport.update({
  id: '/s/$key',
  path: '/s/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEncryptRoute = ApiEncryptRouteImport.update({
  id: '/api/encrypt',
  path: '/api/encrypt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDecryptRoute = ApiDecryptRouteImport.update({
  id: '/api/decrypt',
  path: '/api/decrypt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/prompt': typeof PromptRoute
  '/shiori': typeof ShioriRoute
  '/api/decrypt': typeof ApiDecryptRoute
  '/api/encrypt': typeof ApiEncryptRoute
  '/s/$key': typeof SKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/prompt': typeof PromptRoute
  '/shiori': typeof ShioriRoute
  '/api/decrypt': typeof ApiDecryptRoute
  '/api/encrypt': typeof ApiEncryptRoute
  '/s/$key': typeof SKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/prompt': typeof PromptRoute
  '/shiori': typeof ShioriRoute
  '/api/decrypt': typeof ApiDecryptRoute
  '/api/encrypt': typeof ApiEncryptRoute
  '/s/$key': typeof SKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/prompt'
    | '/shiori'
    | '/api/decrypt'
    | '/api/encrypt'
    | '/s/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/prompt'
    | '/shiori'
    | '/api/decrypt'
    | '/api/encrypt'
    | '/s/$key'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/prompt'
    | '/shiori'
    | '/api/decrypt'
    | '/api/encrypt'
    | '/s/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  PromptRoute: typeof PromptRoute
  ShioriRoute: typeof ShioriRoute
  ApiDecryptRoute: typeof ApiDecryptRoute
  ApiEncryptRoute: typeof ApiEncryptRoute
  SKeyRoute: typeof SKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shiori': {
      id: '/shiori'
      path: '/shiori'
      fullPath: '/shiori'
      preLoaderRoute: typeof ShioriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt': {
      id: '/prompt'
      path: '/prompt'
      fullPath: '/prompt'
      preLoaderRoute: typeof PromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$key': {
      id: '/s/$key'
      path: '/s/$key'
      fullPath: '/s/$key'
      preLoaderRoute: typeof SKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/encrypt': {
      id: '/api/encrypt'
      path: '/api/encrypt'
      fullPath: '/api/encrypt'
      preLoaderRoute: typeof ApiEncryptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/decrypt': {
      id: '/api/decrypt'
      path: '/api/decrypt'
      fullPath: '/api/decrypt'
      preLoaderRoute: typeof ApiDecryptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  PromptRoute: PromptRoute,
  ShioriRoute: ShioriRoute,
  ApiDecryptRoute: ApiDecryptRoute,
  ApiEncryptRoute: ApiEncryptRoute,
  SKeyRoute: SKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
